"use client"
import React, { useState } from 'react'
import TeamCard from '@/components/TeamCard'

function Page({params}) {
    const { slug } = React.use(params);
    const filter = slug;
    console.log(filter);
  const teamMembers = [
    {
      id: 1,
      name: 'Shiv Ranjan Kumar',
      filter: 'flagbearers',
      branch: 'Civil Engineering',
      year: '4th Year',
      position: 'President',
      email: 'shivk.ug22.ce@nitp.ac.in',
      image: '/images/SHIV.jpg',
    },
    {
      id: 2,
      name: 'Ronak Dass',
      filter: 'flagbearers',
      branch: 'Computer Science and Engineering',
      year: '4th Year',
      position: 'Vice President',
      email: 'ronakd.ug22.cs@nitp.ac.in',
      image: '/images/RONAK DASS.jpg',
    },
    {
      id: 3,
      name: 'Harshdeep',
      filter: 'flagbearers',
      branch: 'Civil Engineering',
      year: '4th Year',
      position: 'Treasurer',
      email: 'harshdeep.ug22.ce@nitp.ac.in',
      image: '/images/HARSHDEEP.jpg',
    },
    {
      id: 4,
      name: 'Preety Rani',
      filter: 'flagbearers',
      branch: 'Electrical Engineering',
      year: '4th Year',
      position: 'Secretary',
      email: 'preetyr.ug22.ee@nitp.ac.in',
      image: '/images/PREETY RANI.jpg',
    },
    {
      id: 5,
      name: 'Anusha Tank',
      filter: 'flagbearers',
      branch: 'Civil Engineering',
      year: '4th Year',
      position: 'PR-Coordinator',
      email: 'anushat.ug22.ce@nitp.ac.in',
      image: '/images/ANUSHA TANK.jpg',
    },
    {
      id: 6,
      name: 'Sameer Gupta',
      filter: 'flagbearers',
      branch: 'Electronics and Communication Engineering',
      year: '4th Year',
      position: ' Technical Coordinator',
      email: 'sameerg.ug22.ec@nitp.ac.in',
      image: '/images/SAMEER GUPTA.jpg',
    },
    {
      id: 7,
      name: 'Piyush Kumar',
      filter: 'flagbearers',
      branch: 'Electrical Engineering',
      year: '4th Year',
      position: 'Event Coordinator',
      email: 'piyushk.dd22.ee@nitp.ac.in',
      image: '/images/PIYUSH KUMAR.jpg',
    },
    {
      id: 8,
      name: 'Manab Mondal',
      filter: 'flagbearers',
      branch: 'Electrical Engineering',
      year: '4th Year',
      position: 'Event Coordinator',
      email: 'manabm.dd22.ee@nitp.ac.in',
      image: '/images/MANAV MONDAL.jpg',
    },
    {
      id: 9,
      name: 'Hitesh Parmar',
      filter: 'flagbearers',
      branch: 'Computer Science and Engineering',
      year: '4th Year',
      position: 'Media Coordinator',
      email: 'hiteshp.dd22.cs@nitp.ac.in',
      image: '/images/HITESH.png',
    },
    {
      id: 10,
      name: 'Vaishnavi',
      filter: 'flagbearers',
      branch: 'CSE',
      year: '1st Year',
      position: 'Media Coordinator',
      email: 'anantam@example.com',
      image: '/images/VAISHNAVI.png',
    },
    {
      id: 11,
      name: 'Yuvraj',
      filter: 'flagbearers',
      branch: 'Computer Science and Engineering',
      year: '4th Year',
      position: 'Outreach Coordinator',
      email: 'yuvraj.ug22.cs@nitp.ac.in',
      image: '/images/YUVRAJ.jpg',
    },
    {
      id: 12,
      name: 'Harshit Raj',
      filter: 'flagbearers',
      branch: 'Mechanical Engineering',
      year: '4th Year',
      position: 'Logistics Coordinator',
      email: 'harshitr.ug22.me@nitp.ac.in',
      image: '/images/HARSHIT RAJ.jpg',
    },
    {
      id: 13,
      name: 'Vikash',
      filter: 'flagbearers',
      branch: 'Computer Science and Engineering',
      year: '1st Year',
      position: 'Logistics Coordinator',
      email: 'anantam@example.com',
      image: '/images/VIKASH.jpg',
    },
    {
      id: 14,
      name: 'Aditya Kumar',
      filter: 'flagbearers',
      branch: 'Electronics and Communication Engineering',
      year: '4th Year',
      position: 'Senior Member',
      email: 'adityak.ug22.ec@nitp.ac.in',
      image: '/images/aditya.jpeg',
    },
    {
      id: 15,
      name: 'Garima Kushwaha',
      filter: 'flagbearers',
      branch: 'Mechanical Engineering',
      year: '4th Year',
      position: 'Senior Member',
      email: 'garimak.ug22.me@nitp.ac.in',
      image: '/images/garima.png',
    },
    {
      id: 16,
      name: 'Madduri Hemadruthi',
      filter: 'alumni',
      branch: '',
      year: 'Alumni',
      position: 'President',
      email: '',
      image: '/images/Madduri.jpeg',
    },
    {
      id: 17,
      name: 'Urvashi Kashyap',
      filter: 'alumni',
      branch: '',
      position: 'Vice President',
      year: 'Alumni',
      email: '',
      image: '/images/Urvashi.jpeg',
    },
    {
    id: 18,
    name: 'Rakesh Kumar',
    filter: 'alumni',
    branch: 'Computer Science and Engineering',
    position: 'President',
    year: 'Graduated',
    email: 'rakeshk.ug18.cs@nitp.ac.in',
    image: '/images/Rakesh.jpeg',
  },
    {
      id: 19,
      name: 'Anant',
      filter: 'Alumni',
      branch: '',
      position: 'Content head',
      year: 'Alumni',
      email: '',
      image: '/images/anant.jpeg',
    },
    {
      id: 20,
      name: 'Anjali Kumari',
      filter: 'Alumni',
      branch: '',
      position: 'Event Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Anjali.jpeg',
    },
    {
      id: 21,
      name: 'Sonu Kumar',
      filter: 'alumni',
      branch: '',
      position: 'PR Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/sonu.jpeg',
    },
    {
      id: 22,
      name: 'Ravi Ranjan',
      filter: 'alumni',
      branch: '',
      position: 'Library Incharge',
      year: 'Alumni',
      email: '',
      image: '/images/Ravi.jpeg',
    },
    {
      id: 23,
      name: 'Pravin Pushkar',
      filter: 'alumni',
      branch: '',
      position: 'President',
      year: 'Alumni',
      email: '',
      image: '/images/Pravin.jpeg',
    },
    {
      id: 24,
      name: 'Angel Jain',
      filter: 'alumni',
      branch: '',
      position: 'Vice President',
      year: 'Alumni',
      email: '',
      image: '/images/Angel.jpeg',
    },
    {
      id: 25,
      name: 'Sameer Chaudhary',
      filter: 'alumni',
      branch: '',
      position: 'Secretary',
      year: 'Alumni',
      email: '',
      image: '/images/Sameer.jpeg',
    },
    {
      id: 26,
      name: 'Ajit Kumar',
      filter: 'alumni',
      branch: '',
      position: 'Treasurer',
      year: 'Alumni',
      email: '',
      image: '/images/Ajit.jpeg',
    },
    {
      id: 27,
      name: 'Saresh',
      filter: 'alumni',
      branch: '',
      position: 'Media and Content Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Saresh.jpeg',
    },
    {
      id: 28,
      name: 'Ashish Kumar Jha',
      filter: 'alumni',
      branch: '',
      position: 'PR Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Ashish.jpeg',
    },
    {
      id: 29,
      name: 'Rathod Niharika',
      filter: 'alumni',
      branch: '',
      position: 'Event Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Rathod.jpeg',
    },
    {
      id: 30,
      name: 'S Abbas Haider',
      filter: 'alumni',
      branch: '',
      position: 'Logistics Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Abbas.jpeg',
    },
    {
      id: 31,
      name: 'Ajay Siraw',
      filter: 'alumni',
      branch: '',
      position: 'Joint Treasurer',
      year: 'Alumni',
      email: '',
      image: '/images/Ajay.jpeg',
    },
    {
      id: 32,
      name: 'Aman kesari',
      filter: 'alumni',
      branch: '',
      position: 'App Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Aman.jpeg',
    },
    {
      id: 33,
      name: 'Aditya Kumar',
      filter: 'alumni',
      branch: '',
      position: 'Event Co Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/AdityaK.jpeg',
    },
    {
      id: 34,
      name: 'Abhishek kumar',
      filter: 'alumni',
      branch: '',
      position: 'Web Coordintor',
      year: 'Alumni',
      email: '',
      image: '/images/Abhishek.jpeg',
    },
    {
      id: 35,
      name: 'Achyut Singh',
      filter: 'alumni',
      branch: '',
      position: 'Web Co Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Achyut.jpeg',
    },
    {
      id: 36,
      name: 'Nisarg Patel',
      filter: 'alumni',
      branch: '',
      position: 'Logistic Co Coordinator',
      year: 'Alumni',
      email: '',
      image: '/images/Nisarg.jpeg',
    },
//    {
//   id: 37,
//   name: 'Abhisth',
//   filter: 'batch-24',
//   branch: 'Architecture',
//   position: 'Member',
//   year: '2ⁿᵈ year',
//   email: '',
//   image: '/images/Abhisth.jpeg',
// },
{
  id: 38,
  name: 'Alekh Bhardwaj',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'Design Team',
  year: '2ⁿᵈ year',
  email: 'alekhb.ug24.ce@nitp.ac.in',
  image: '/images/Alekh.jpeg',
},
{
  id: 39,
  name: 'Anantam Aftab',
  filter: 'batch-24',
  branch: 'Computer Science Engineering',
  position: 'Web Team',
  year: '2ⁿᵈ year',
  email: 'anantama.ug24.cs@nitp.ac.in',
  image: '/images/Anantam.jpeg',
},
{
  id: 40,
  name: 'Ayush',
  filter: 'batch-24',
  branch: 'Computer Science Engineering',
  position: 'Web Team',
  year: '2ⁿᵈ year',
  email: 'ayushb.ug24.cs@nitp.ac.in',
  image: '/images/Ayush.jpg',
},
{
  id: 41,
  name: 'Disha Shiromani',
  filter: 'batch-24',
  branch: 'Electrical Engineering',
  position: 'Technical Team',
  year: '2ⁿᵈ year',
  email: 'dishas.ug24.ee@nitp.ac.in',
  image: '/images/Disha.jpeg',
},
{
  id: 42,
  name: 'Dishant',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'Outreach Team',
  year: '2ⁿᵈ year',
  email: 'dishantp.ug24.ce@nitp.ac.in',
  image: '/images/Dishant.jpeg',
},
{
  id: 43,
  name: 'Gaurav',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'PR Team',
  year: '2ⁿᵈ year',
  email: 'gauravs.ug24.ce@nitp.ac.in',
  image: '/images/Gaurav.jpeg',
},
{
  id: 44,
  name: 'Harsh Kapadiya',
  filter: 'batch-24',
  branch: 'Computer Science Engineering',
  position: 'Design Team ',
  year: '2ⁿᵈ year',
  email: 'harsh.cs.ug24@nitp.ac.in ',
  image: '/images/Harsh.jpeg',
},
{
  id: 45,
  name: 'Harshitaa Bhanusali',
  filter: 'batch-24',
  branch: 'Electronics and Communication Engineering',
  position: 'Web team',
  year: '2ⁿᵈ year',
  email: 'harshitab.ug24.ec@nitp.ac.in',
  image: '/images/Harshita.jpeg',
},
{
  id: 46,
  name: 'Jay kant Singh',
  filter: 'batch-24',
  branch: 'Mechatronics and Automation Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: 'jays.ug24.mae@nitp.ac.in',
  image: '/images/Jay.jpeg',
},
{
  id: 47,
  name: 'Jubin Echhpujani',
  filter: 'batch-24',
  branch: 'Electronics and Communication Engineering',
  position: 'Outreach Team',
  year: '2ⁿᵈ year',
  email:'jubine.ug24.ec@nitp.ac.in',
  image: '/images/Jubin.jpeg',
},
{
  id: 48,
  name: 'Mohit Minz',
  filter: 'batch-24',
  branch: 'Electronics and Communication Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: 'mohitm.ug24.ec@nitp.ac.in',
  image: '/images/Mohit.jpeg',
},
{
  id: 49,
  name: 'Naincy Soni',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: 'Naincys.ug24.ce@nitp.ac.in',
  image: '/images/Naincy.jpeg',
},
{
  id: 50,
  name: 'Nidhi Agrawal',
  filter: 'batch-24',
  branch: 'Mechatronics and Automation Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: '',
  image: '/images/Nidhi.jpeg',
},
{
  id: 51,
  name: 'Sagar',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: '',
  image: '/images/Sagar(1).jpeg',
},
{
  id: 52,
  name: 'Sagar',
  filter: 'batch-24',
  branch: 'Mechanical Engineering',
  position: 'Design Team ',
  year: '2ⁿᵈ year',
  email: '',
  image: '/images/Sagar.jpeg',
},
// {
//   id: 53,
//   name: 'Saurav',
//   filter: 'batch-24',
//   branch: 'Civil Engineering',
//   position: 'Member',
//   year: '2ⁿᵈ year',
//   email: '',
//   image: '/images/Saurav.jpeg',
// },
{
  id: 54,
  name: 'Shrami Mathur',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: 'shramim.ug24.ce@nitp.ac.in',
  image: '/images/Shrami.jpg',
},
{
  id: 55,
  name: 'Shivani Chaudhary',
  filter: 'batch-24',
  branch: 'Computer Science Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: 'shivanik.ug24.cs@nitp.ac.in',
  image: '/images/Shivani.jpeg',
},
{
  id: 56,
  name: 'Sujay Kumar Singh',
  filter: 'batch-24',
  branch: 'Computer Science Engineering',
  position: 'Technical Team',
  year: '2ⁿᵈ year',
  email: 'sujays.ug24.cs@nitp.ac.in',
  image: '/images/Sujay.jpeg',
},
{
  id: 57,
  name: 'Suryansh Shukla',
  filter: 'batch-24',
  branch: 'Civil Engineering',
  position: 'Member',
  year: '2ⁿᵈ year',
  email: 'suryanshs.ug24.ce@nitp.ac.in',
  image: '/images/Suryansh.jpeg',
},
// {
//   id: 58,
//   name: 'Utkarsh Sharma',
//   filter: 'batch-24',
//   branch: 'Mechanical Engineering',
//   position: 'Member',
//   year: '2ⁿᵈ year',
//   email: '',
//   image: '/images/Utkarsh.jpeg',
// },
{
    id: 59,
    name: 'Prince Kumar Jha',
    filter: 'batch-23',
    branch: 'Computer Science and Engineering',
    position: 'Content Team',
    year: '3ʳᵈ year',
    email: 'princej.ug23.cs@nitp.ac.in',
    image: '/images/Prince.jpeg',
  },
  {
    id: 60,
    name: 'Ankesh Parashar',
    filter: 'batch-23',
    branch: 'Mechanical Engineering',
    position: 'Outreach Team',
    year: '3ʳᵈ year',
    email: 'ankeshp.ug23.me@nitp.ac.in',
    image: '/images/Ankesh.jpeg',
  },
  {
    id: 61,
    name: 'Laxmi Shukla',
    filter: 'batch-23',
    branch: 'Mechanical Engineering',
    position: 'PR Team',
    year: '3ʳᵈ year',
    email: 'laxmishukla6263@gmail.com',
    image: '/images/Laxmi.jpg',
  },
  {
    id: 62,
    name: 'Adarsh Kumar Dubey',
    filter: 'batch-23',
    branch: 'Electronics and Communication Engineering',
    position: 'PR Team',
    year: '3ʳᵈ year',
    email: 'adarshd.ug23.ec@nitp.ac.in',
    image: '/images/Adarsh.jpeg',
  },
  {
    id: 63,
    name: 'Neritya Gupta',
    filter: 'batch-23',
    branch: 'Civil Engineering',
    position: 'Technical Team ',
    year: '3ʳᵈ year',
    email: 'nerityagupta123@gmail.com',
    image: '/images/Neritya.jpeg',
  },
  {
    id: 64,
    name: 'Sidram Dubalgunde',
    filter: 'batch-23',
    branch: 'Architecture',
    position: 'Design Team ',
    year: '3ʳᵈ year',
    email: 'Sidramd.ug23.ar@nitp.ac.in',
    image: '/images/Sidram.jpeg',
  },
  
  {
    id: 66,
    name: 'Vasu Choudhari',
    filter: 'batch-23',
    branch: 'Computer Science and Engineering',
    position: 'Web Team',
    year: '3ʳᵈ year',
    email: 'vasuc.ug23.cs@nitp.ac.in',
    image: '/images/Vasu.jpg',
  },
  {
    id: 67,
    name: 'Ujjwal Choubey',
    filter: 'batch-23',
    branch: 'Computer Science and Engineering',
    position: 'Technical Team',
    year: '3ʳᵈ year',
    email: 'ujjwalc.ug23.cs@nitp.ac.in',
    image: '/images/Ujjwal.jpeg',
  },
  {
    id: 68,
    name: 'Aditya Anand',
    filter: 'batch-23',
    branch: 'Civil Engineering',
    position: 'Outreach Team',
    year: '3ʳᵈ year',
    email: 'adityaa.ug23.ce@nitp.ac.in',
    image: '/images/Aditya23.jpeg',
  },
  {
    id: 69,
    name: 'Trinetra Kumar',
    filter: 'batch-23',
    branch: 'Electronics and Communication Engineering',
    position: 'Technical Team',
    year: '3ʳᵈ year',
    email: 'trinetrak.ug23.ec@nitp.ac.in',
    image: '/images/Trinetra.jpeg',
  },
  {
    id: 70,
    name: 'Prakhar Srivastav',
    filter: 'batch-23',
    branch: 'Civil Engineering',
    position: 'Design Team',
    year: '3ʳᵈ year',
    email: 'prakhars.ug23.ce@nitp.ac.in',
    image: '/images/Prakhar.jpeg',
  },
  {
    id: 71,
    name: 'Archi Singh',
    filter: 'batch-23',
    branch: 'Mechanical Engineering',
    position: 'PR and Outreach Team',
    year: '3ʳᵈ year',
    email: 'archis.ug23.me@nitp.ac.in',
    image: '/images/Archi.jpeg',
  }

  ];

    // Only show members matching the filter from the URL
    const filteredMembers = teamMembers.filter(m => m.filter === filter);

    return (
        <div>
            <h1 className="mt-2 text-4xl my-4 text-center fraunces text-yellow-400 drop-shadow">
                Meet the Cool Crew
            </h1>
            <TeamCard members={filteredMembers} />
        </div>
    )
}

export default Page
